services:
  db:
    image: mysql:8.0
    container_name: auth_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: authdb
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    container_name: auth_api
    restart: unless-stopped
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./api:/usr/src/app
    command: ["npm","run","start:prod"]

  front:
    build:
      context: ./front
    container_name: auth_front
    restart: unless-stopped
    env_file:
      - ./front/.env
    depends_on:
      - api
    ports:
      - "3000:80"
    # static nginx image serves build output
volumes:
  db_data:
