version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db-entrevista
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: authdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: ./api
    container_name: api-entrevista
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
    depends_on:
      - db
    volumes:
      - ./api/src:/app/src
      - ./api/.env:/app/.env
      - /app/node_modules

volumes:
  db_data:
