import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './providers'
import { isAuthenticated } from '@/auth/auth'
import { redirect } from 'next/navigation'
import { headers } from 'next/headers'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const pathname = (await headers()).get('x-pathname') || '/auth/sign-in'
  const publicRoutes = ['/auth/sign-in', '/auth/sign-up']
 
  if (!await isAuthenticated() && !(publicRoutes.includes(pathname))) {
    console.log('redirecting to sign-in from layout')
    redirect('/auth/sign-in')
  }
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
