services:
  api:
    build: .
    container_name: api-entrevista-dev
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src        # hot reload das mudanças
      - /app/node_modules     # evita sobrescrever node_modules
